### ISSUE TITLE
Add ``check_random_states`` to ``__init__.py`` in utils submodule

### ISSUE THREAD

**Issue by joaopfonseca** [joaopfonseca/ml-research#37]
This function can be useful at time, yet is not made easy to access. It is defined in ``mlresearch.utils._check_pipelines.py``.

**Comment by ArcturusMotors** [comment]
So the issue is to just move check_random_states function to init?

**Comment by joaopfonseca** [comment]
Yes, so importing the function in the init file and adding it to the ``__all__`` list. In addition, the corresponding entry in the API documentation page (https://github.com/joaopfonseca/ml-research/blob/master/docs/api.rst) should be added.

**Comment by ArcturusMotors** [comment]
Alright. Created a pull request

**Comment by joaopfonseca** [comment]
Merged PR #38. Thank you!
